# Generated by Django 5.1.6 on 2025-03-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default-image.jpg', null=True, upload_to='products/'),
        ),
    ]
